# Generated by Django 4.0.4 on 2022-06-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_part_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='part',
            field=models.ManyToManyField(to='core.part'),
        ),
    ]
